### ISSUE TITLE
SAM application bridge won't run at startup

### ISSUE THREAD

**Issue by gasull** [i2p/i2p.i2p#49]
Even if I configure the SAM application bridge to run at startup on http://127.0.0.1:7657/configclients, it will not run unless I manually start it on this page.

**Comment by eyedeekay** [comment]
Can't reproduce the issue here. Please provide more information if you can.

**Comment by APT37** [comment]
The SAM Bridge config seems not to acknowledge the host IP changing after setting it on the initial run.

The actual IP is `172.18.0.20` instead of `172.18.0.34` - but this change did not get picked up.

<img width="998" height="42" alt="Image" src="https://github.com/user-attachments/assets/b775889e-a026-458e-86a0-4db864b1e929" />

If you're also running I2P in Docker, where IP changes can go unnoticed, you know where to look.

```
2026/01/04 00:58:11.359 CRIT [SAMBridge ] …igClientsHandler: Error starting up the client class net.i2p.sam.SAMBridge
2026/01/04 00:58:11.359 ERROR [SAMBridge ] …RouterAppManager: Client net.i2p.sam.SAMBridge@3c735b36 failed to start
     java.net.BindException: Address not available
     at java.base/sun.nio.ch.Net.bind0(Native Method)
     at java.base/sun.nio.ch.Net.bind(Net.java:555)
     at java.base/sun.nio.ch.ServerSocketChannelImpl.netBind(ServerSocketChannelImpl.java:337)
     at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:294)
     at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:89)
     at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:81)
     at net.i2p.sam.SAMBridge.openSocket(SAMBridge.java:232)
     at net.i2p.sam.SAMBridge.startup(SAMBridge.java:444)
     at net.i2p.router.startup.RouterAppManager.addAndStart(RouterAppManager.java:54)
     at net.i2p.router.startup.LoadClientAppsJob$RunApp.run(LoadClientAppsJob.java:309)
     at java.base/java.lang.Thread.run(Thread.java:833)
     at net.i2p.util.I2PThread.run(I2PThread.java:103)
```

**Comment by WaxySteelWorm** [comment]
As part of an ongoing GitHub cleanup, I2P is closing this issue. If the issue remains relevant, please reopen it.
